version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: borya2072/yamdb:latest
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/ 
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
    ports:
      - "80:80"
volumes:
  postgres_data: 
  static_value:
  media_value:
